gpt-4o:
    import: "./openai-chat.yaml"
    parameters:
        name: "gpt-4o"
        body:
            model: "gpt-4o"
            max_tokens: 512

qwq-32b:
    import: "./qwq.yaml"
    parameters:
        name: "qwq-32b"
        body:
            model: "qwq-32b"
            max_tokens: 8192